version: '3.9'

services:
  vue:
    build: ./vue
    ports:
      - "8080:8080"
    volumes:
      - ./vue/src:/vue/src
      - ./vue/package.json:/vue/package.json
    command: npm run serve

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vue
